server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flowpay_dev
    username: flowpay
    password: flowpay
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        linger.ms: 0
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.flowpay.*
        spring.json.value.default.type: com.flowpay.kafka.dto.PaymentEvent

  data:
    redis:
      host: localhost
      port: 6379
      password: redispass
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 2
          max-wait: 2000ms

logging:
  level:
    root: INFO
    com.flowpay: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,mappings
  endpoint:
    health:
      show-details: always
      show-components: always
