apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flowpay-core
  namespace: flowpay
  labels:
    app.kubernetes.io/name: flowpay-core
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flowpay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flowpay-core
  minReplicas: 3
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
      selectPolicy: Min
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_server_requests_per_second
        target:
          type: AverageValue
          averageValue: "1000"
