CREATE TABLE transactions (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    reference_id        VARCHAR(64)     NOT NULL,
    idempotency_key     VARCHAR(64),
    sender_id           UUID            NOT NULL,
    receiver_id         UUID            NOT NULL,
    sender_account_id   UUID            NOT NULL,
    receiver_account_id UUID            NOT NULL,
    amount              DECIMAL(19, 4)  NOT NULL,
    currency            VARCHAR(3)      NOT NULL,
    fee                 DECIMAL(19, 4)  NOT NULL DEFAULT 0.0000,
    status              VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    type                VARCHAR(30)     NOT NULL,
    description         VARCHAR(500),
    failure_reason      VARCHAR(500),
    metadata            JSONB,
    retry_count         INT             NOT NULL DEFAULT 0,
    processed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),

    CONSTRAINT uq_transactions_reference_id UNIQUE (reference_id),
    CONSTRAINT uq_transactions_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_transactions_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk_transactions_receiver FOREIGN KEY (receiver_id) REFERENCES users (id),
    CONSTRAINT fk_transactions_sender_account FOREIGN KEY (sender_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_transactions_receiver_account FOREIGN KEY (receiver_account_id) REFERENCES accounts (id),
    CONSTRAINT chk_transactions_amount CHECK (amount > 0),
    CONSTRAINT chk_transactions_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED', 'CANCELLED')),
    CONSTRAINT chk_transactions_type CHECK (type IN ('TRANSFER', 'PAYMENT', 'DEPOSIT', 'WITHDRAWAL', 'REFUND')),
    CONSTRAINT chk_transactions_currency CHECK (currency ~ '^[A-Z]{3}$')
);
